version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: deploy/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      EXPORTER_HOST: jaeger
    depends_on:
      - jaeger

  client:
    build:
      context: .
      dockerfile: deploy/client/Dockerfile
    environment:
      EXPORTER_HOST: jaeger
      SERVER_HOST: server
    depends_on:
      - jaeger
      - server

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
